MVP of new laptop script
- installs XCode CLI
- sets up ~/.ksr.rc
- installs & configures homebrew and some dependencies
- configures rbenv

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Welcome to the thoughtbot laptop script!
+# Welcome to the Kickstarter laptop script!
 # Be prepared to turn your laptop (or desktop, no haters here)
 # into an awesome development machine.
 
@@ -11,81 +11,45 @@ fancy_echo() {
   printf "\n$fmt\n" "$@"
 }
 
-append_to_zshrc() {
-  local text="$1" zshrc
-  local skip_new_line="${2:-0}"
-
-  if [ -w "$HOME/.zshrc.local" ]; then
-    zshrc="$HOME/.zshrc.local"
-  else
-    zshrc="$HOME/.zshrc"
-  fi
-
-  if ! grep -Fqs "$text" "$zshrc"; then
-    if [ "$skip_new_line" -eq 1 ]; then
-      printf "%s\n" "$text" >> "$zshrc"
-    else
-      printf "\n%s\n" "$text" >> "$zshrc"
-    fi
-  fi
-}
-
 # shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+trap 'ret=$?; test $ret -ne 0 && printf "Setup failed.\n\n" >&2; exit $ret' EXIT
 
 set -e
 
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
+##
+# Install XCode and XCode Command line tools
+if [ ! -d /Applications/Xcode.app ]
+then
+  XCODE_URL='http://itunes.apple.com/us/app/xcode/id497799835'
+  echo "Missing XCode. Install XCode from the Mac App Store:"
+  echo $XCODE_URL
+  open $XCODE_URL
+  exit 1
 fi
 
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
+# need a way to check for this and automate:
+# sudo xcodebuild -license
 
-# shellcheck disable=SC2016
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+# XCode command-line tools
+# From http://stackoverflow.com/a/15371967
+while ! pkgutil --pkg-info=com.apple.pkg.CLTools_Executables > /dev/null; do
 
-HOMEBREW_PREFIX="/usr/local"
-
-if [ -d "$HOMEBREW_PREFIX" ]; then
-  if ! [ -r "$HOMEBREW_PREFIX" ]; then
-    sudo chown -R "$LOGNAME:admin" /usr/local
-  fi
-else
-  sudo mkdir "$HOMEBREW_PREFIX"
-  sudo chflags norestricted "$HOMEBREW_PREFIX"
-  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
-fi
-
-case "$SHELL" in
-  */zsh) : ;;
-  *)
-    fancy_echo "Changing your shell to zsh ..."
-      chsh -s "$(which zsh)"
-    ;;
-esac
-
-gem_install_or_update() {
-  if gem list "$1" --installed > /dev/null; then
-    gem update "$@"
+  if [ -z "$xcode_cli_installing" ]; then
+    echo "Installing XCode command line tools."
+    xcode-select --install
+    echo "Waiting XCode command line tools..."
+    xcode_cli_installing='yes'
   else
-    gem install "$@"
-    rbenv rehash
+    sleep 1
   fi
-}
 
+done
+
+##
+# Install homebrew
 if ! command -v brew >/dev/null; then
   fancy_echo "Installing Homebrew ..."
-    curl -fsS \
-      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-
-    append_to_zshrc '# recommended by brew doctor'
-
-    # shellcheck disable=SC2016
-    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
-
-    export PATH="/usr/local/bin:$PATH"
+  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 fi
 
 if brew list | grep -Fq brew-cask; then
@@ -93,70 +57,79 @@ if brew list | grep -Fq brew-cask; then
   brew uninstall --force brew-cask
 fi
 
-fancy_echo "Updating Homebrew formulae ..."
-brew update
-brew bundle --file=- <<EOF
-tap "thoughtbot/formulae"
+fancy_echo "Checking Homebrew formulae ..."
+brew bundle --file=- > /dev/null <<EOF
 tap "homebrew/services"
 
-# Unix
-brew "ctags"
 brew "git"
 brew "openssl"
-brew "rcm"
-brew "reattach-to-user-namespace"
-brew "the_silver_searcher"
-brew "tmux"
-brew "vim"
-brew "zsh"
-
-# Heroku
-brew "heroku-toolbelt"
-brew "parity"
-
-# GitHub
-brew "hub"
-
-# Image manipulation
-brew "imagemagick"
-
-# Testing
-brew "qt"
-
-# Programming languages
-brew "libyaml" # should come after openssl
-brew "node"
 brew "rbenv"
 brew "ruby-build"
-
-# Databases
-brew "postgres", restart_service: true
-brew "redis", restart_service: true
 EOF
 
-fancy_echo "Configuring Ruby ..."
-find_latest_ruby() {
-  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
-}
-
-ruby_version="$(find_latest_ruby)"
-# shellcheck disable=SC2016
-append_to_zshrc 'eval "$(rbenv init - --no-rehash)"' 1
+fancy_echo "Configuring rbenv init ..."
 eval "$(rbenv init -)"
 
-if ! rbenv versions | grep -Fq "$ruby_version"; then
-  RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install -s "$ruby_version"
+fancy_echo "Restarting background brew updater..."
+##
+# Automatically run `brew update` every 2 hours
+# This saves ~20 seconds on subsequent runs b/c we don't have to wait for `brew update`
+cat > ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist <<- EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+  <dict>
+    <key>Label</key>
+    <string>com.kickstarter.homebrew-updater</string>
+    <key>ProgramArguments</key>
+    <array>
+    <string>/usr/local/bin/brew</string>
+    <string>update</string>
+    </array>
+
+    <key>RunAtLoad</key>
+    <true/>
+
+    <key>StartInterval</key>
+    <integer>7200</integer>
+  </dict>
+</plist>
+EOF
+
+launchctl unload ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist 2> /dev/null
+launchctl load   ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist
+
+##
+# source ~/.ksr.rc from shell's rc file
+case $(basename "$SHELL") in
+  bash )
+    profile="$HOME/.bashrc"
+    ;;
+  zsh )
+    profile="$HOME/.zshrc"
+    ;;
+  * )
+    echo 'Unrecognized shell'
+    ;;
+  esac
+
+cmd='if [ -e ~/.ksr.rc ]; then source ~/.ksr.rc; fi # Provisioned by ksr laptop script'
+if ! grep -Fqs "$cmd" "$profile"; then
+  fancy_echo "Adding ~/.ksr.rc to $profile"
+  printf "\n$cmd\n" >> "$profile"
 fi
 
-rbenv global "$ruby_version"
-rbenv shell "$ruby_version"
-gem update --system
-gem_install_or_update 'bundler'
-number_of_cores=$(sysctl -n hw.ncpu)
-bundle config --global jobs $((number_of_cores - 1))
+cat > ~/.ksr.rc <<-"EOF"
+# Kickstarter init commands provisioned by the laptop script.
+# Changes will be overwritten.
 
-if [ -f "$HOME/.laptop.local" ]; then
-  fancy_echo "Running your customizations from ~/.laptop.local ..."
-  # shellcheck disable=SC1090
-  . "$HOME/.laptop.local"
+# Initialize rbenv
+eval "$(rbenv init -)"
+
+if [[ ! "$PATH" =~ "/usr/local/bin" ]]; then
+  export PATH="/usr/local/bin:$PATH"
 fi
+EOF
+
+
+fancy_echo "Laptop setup succeeded."
