Much prettier output

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -4,17 +4,46 @@
 # Be prepared to turn your laptop (or desktop, no haters here)
 # into an awesome development machine.
 
-fancy_echo() {
-  local fmt="$1"; shift
+set -e
 
-  # shellcheck disable=SC2059
-  printf "\n$fmt\n" "$@"
+cat > ~/.ksr_functions.sh <<-"EOF"
+# Helpful functions for from the kickstarter
+# laptop script
+
+# Print a cyan info message
+info() {
+  printf "\n%s ... " "$@"
+}
+
+print_check() {
+  printf "✅ \n"
+}
+
+# Print a happy green message
+succeed() {
+  printf "\n$(tput bold)$(tput setaf 2)%s$(tput sgr0)" "$@"
+  printf "\n❤️  💛  💚  💙  💜 \n"
+}
+
+
+# Print a red error
+fail() {
+  printf "\n\n$(tput bold)$(tput setaf 1)%s$(tput sgr0)\n" "$@"
+}
+EOF
+
+source ~/.ksr_functions.sh
+
+exit_message() {
+  ret=$?
+ if  [ $ret -ne 0 ]; then
+   fail "Setup failed. 💔  " >&2
+ fi
+ exit $ret
 }
 
 # shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "Setup failed.\n\n" >&2; exit $ret' EXIT
-
-set -e
+trap exit_message EXIT
 
 ##
 # Install XCode and XCode Command line tools
@@ -48,16 +77,18 @@ done
 ##
 # Install homebrew
 if ! command -v brew >/dev/null; then
-  fancy_echo "Installing Homebrew ..."
+  info "Installing Homebrew"
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  print_check
 fi
 
 if brew list | grep -Fq brew-cask; then
-  fancy_echo "Uninstalling old Homebrew-Cask ..."
+  info "Uninstalling old Homebrew-Cask"
   brew uninstall --force brew-cask
+  print_check
 fi
 
-fancy_echo "Checking Homebrew formulae ..."
+info "Checking Homebrew formulae"
 brew bundle --file=- > /dev/null <<EOF
 tap "homebrew/services"
 
@@ -66,11 +97,13 @@ brew "openssl"
 brew "rbenv"
 brew "ruby-build"
 EOF
+print_check
 
-fancy_echo "Configuring rbenv init ..."
+info "Configuring rbenv init"
 eval "$(rbenv init -)"
+print_check
 
-fancy_echo "Restarting background brew updater..."
+info "Restarting background brew updater"
 ##
 # Automatically run `brew update` every 2 hours
 # This saves ~20 seconds on subsequent runs b/c we don't have to wait for `brew update`
@@ -98,6 +131,7 @@ EOF
 
 launchctl unload ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist 2> /dev/null
 launchctl load   ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist
+print_check
 
 ##
 # Install Pow web server
@@ -109,6 +143,19 @@ fi
 
 ##
 # source ~/.ksr.rc from shell's rc file
+
+cat > ~/.ksr.rc <<-"EOF"
+# Kickstarter init commands provisioned by the laptop script.
+# Changes will be overwritten.
+
+# Initialize rbenv
+eval "$(rbenv init -)"
+
+if [[ ! "$PATH" =~ "/usr/local/bin" ]]; then
+  export PATH="/usr/local/bin:$PATH"
+fi
+EOF
+
 case $(basename "$SHELL") in
   bash )
     profile="$HOME/.bashrc"
@@ -123,21 +170,11 @@ case $(basename "$SHELL") in
 
 cmd='if [ -e ~/.ksr.rc ]; then source ~/.ksr.rc; fi # Provisioned by ksr laptop script'
 if ! grep -Fqs "$cmd" "$profile"; then
-  fancy_echo "Adding ~/.ksr.rc to $profile"
+  info "Adding ~/.ksr.rc to $profile"
   printf "\n$cmd\n" >> "$profile"
+  print_check
 fi
 
-cat > ~/.ksr.rc <<-"EOF"
-# Kickstarter init commands provisioned by the laptop script.
-# Changes will be overwritten.
-
-# Initialize rbenv
-eval "$(rbenv init -)"
-
-if [[ ! "$PATH" =~ "/usr/local/bin" ]]; then
-  export PATH="/usr/local/bin:$PATH"
-fi
-EOF
-
-
-fancy_echo "Laptop setup succeeded."
+info "Reticulating splines"
+print_check
+succeed "Laptop setup successful!"
